# Generated by Django 5.1.2 on 2024-11-09 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.PositiveBigIntegerField(primary_key='True', serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
                ('identity', models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('operator', 'Operator')], default='customer', max_length=10)),
            ],
        ),
    ]
